global using Application;
global using Infrastructure.Data;
global using MediatR;
global using Microsoft.AspNetCore.Localization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Razor;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using System.Globalization;
